# Generated by Django 4.1.4 on 2023-01-22 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='comment',
            field=models.TextField(max_length=1000, null=True),
        ),
    ]
